# Generated by Django 4.2 on 2023-04-12 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('region', models.CharField(choices=[('서울', '서울'), ('강원도', '강원도'), ('경기도', '경기도'), ('충청도', '충청도'), ('전라도', '전라도'), ('경상도', '경상도'), ('제주도', '제주도')], max_length=3)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('post', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'my_post',
            },
        ),
    ]
